### ISSUE TITLE
OOP-1-review-2022-10-16

### ISSUE THREAD

**Issue by hamerlinski** [Hajk0/oop-put-course#1]
**Task 1**
- [x] Proper communication/interaction between classes and objects is missing.
- [x] Rename repository to **oop-put-course**
- [x] Rename file to task1.cpp
- [x] Format code properly
- [x] Add file extension
